//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int Sender_id { get; set; }
        public int Receiver_id { get; set; }
        public string Message { get; set; }
        public bool Is_seen { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
