//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_log
    {
        public int Id { get; set; }
        public string Current_status { get; set; }
        public string Previous_status { get; set; }
        public string Description { get; set; }
        public int Idea_id { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
    }
}
